# Generated by Django 3.0.5 on 2020-04-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutoriL_title', models.CharField(max_length=200)),
                ('tutoriL_content', models.TextField()),
                ('tutoriL_published', models.DateField(verbose_name='date published')),
            ],
        ),
    ]
