# Generated by Django 3.0.5 on 2020-05-18 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorial',
            old_name='tutoriL_content',
            new_name='tutorial_content',
        ),
        migrations.RenameField(
            model_name='tutorial',
            old_name='tutoriL_published',
            new_name='tutorial_published',
        ),
        migrations.RenameField(
            model_name='tutorial',
            old_name='tutoriL_title',
            new_name='tutorial_title',
        ),
    ]
