# Generated by Django 3.0.5 on 2020-04-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0002_destination_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='offer',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
