# Generated by Django 3.0.5 on 2020-04-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
