# Generated by Django 3.0.5 on 2020-04-28 08:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200428_0518'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestwork',
            name='class_name',
            field=models.CharField(choices=[('A', 'All'), ('P', 'Photoshop'), ('K', 'Branding'), ('C', 'Fashion')], default=django.utils.timezone.now, max_length=1),
            preserve_default=False,
        ),
    ]
