# Generated by Django 3.0.5 on 2020-04-28 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_latestwork_class_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='latestwork',
            name='class_name',
        ),
    ]
