# Generated by Django 3.0.5 on 2020-04-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_latestwork_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestwork',
            name='class_name',
            field=models.CharField(choices=[('A', 'All'), ('P', 'Photoshop'), ('K', 'Branding'), ('C', 'Fashion')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
