# Generated by Django 3.0.5 on 2020-04-29 10:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200429_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, height_field='224px', upload_to='pics', width_field='370px'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='short_desc',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
