# Generated by Django 3.0.5 on 2020-04-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20200429_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='short_desc',
            field=models.CharField(max_length=50),
        ),
    ]
